// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIv-8TczeF3iDOUKIV69hLUoi4prZ0yWc',
    appId: '1:346466899535:web:6fc0436c6aa5c71950fc3a',
    messagingSenderId: '346466899535',
    projectId: 'happyfoodapp-f3dfe',
    authDomain: 'happyfoodapp-f3dfe.firebaseapp.com',
    storageBucket: 'happyfoodapp-f3dfe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWYs7DCgTj0gXwbSqG2KMtl-9cACY4hzA',
    appId: '1:346466899535:android:966b08917a63a1b350fc3a',
    messagingSenderId: '346466899535',
    projectId: 'happyfoodapp-f3dfe',
    storageBucket: 'happyfoodapp-f3dfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAenZu0E2e3GxlO7qjiO2BJBkI6E60s_fw',
    appId: '1:346466899535:ios:241d850a4fb15be550fc3a',
    messagingSenderId: '346466899535',
    projectId: 'happyfoodapp-f3dfe',
    storageBucket: 'happyfoodapp-f3dfe.appspot.com',
    iosBundleId: 'com.example.happyFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAenZu0E2e3GxlO7qjiO2BJBkI6E60s_fw',
    appId: '1:346466899535:ios:d165ff1d4f726ff550fc3a',
    messagingSenderId: '346466899535',
    projectId: 'happyfoodapp-f3dfe',
    storageBucket: 'happyfoodapp-f3dfe.appspot.com',
    iosBundleId: 'com.example.happyFood.RunnerTests',
  );
}
